DROP SEQUENCE MYSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYSEQ;
CREATE TABLE MYBOARD(

MYNO NUMBER PRIMARY KEY,
MYNAME VARCHAR2(1000) NOT NULL,
MYTITLE VARCHAR2(2000) NOT NULL,
MYCONTENT VARCHAR2(4000) NOT NULL,
MYDATE DATE NOT NULL

);

SELECT *
FROM MYBOARD;

INSERT INTO MYBOARD
VALUES(MYSEQ.NEXTVAL, '관리자', 'TEST글입니다.','테스트 글이다.', SYSDATE);

SELECT MYNO, MYNAME, MYTITLE, MYCONTENT, MYDATE
FROM MYBOARD;

UPDATE MYBOARD SET MYTITLE = 'ISLAND', MYCONTENT = 'FIRST ALBUM' WHERE MYNO = 2;