DROP TABLE MDBOARD;

CREATE SEQUENCE MDSEQUENCE;

CREATE TABLE MDBOARD(
SEQ NUMBER PRIMARY KEY,
WRITER VARCHAR2(100) NOT NULL,
TITLE VARCHAR2(200) NOT NULL,
CONTENT VARCHAR2(1000) NOT NULL,
REGDATE DATE NOT NULL
)

SELECT *
FROM MDBOARD;

INSERT INTO MDBOARD
VALUES(MDSEQUENCE.NEXTVAL, 'Beatles', 'White', 'Last Album', SYSDATE);

SELECT *
FROM MDBOARD;