DROP SEQUENCE CALBOARDSEQ;
DROP TABLE CALBOARD;

CREATE SEQUENCE CALBOARDSEQ;

CREATE TABLE CALBOARD(
SEQ NUMBER PRIMARY KEY,
ID VARCHAR2(1000) NOT NULL,
TITLE VARCHAR2(2000) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
MDATE VARCHAR2(12) NOT NULL,
REGDATE DATE NOT NULL

);

SELECT * FROM CALBOARD;


INSERT INTO CALBOARD
VALUES(CALBOARDSEQ.NEXTVAL,?,?,?,?,SYSDATE);