DROP SEQUENCE CALBOARDSEQ;
DROP TABLE CALBOARD;

CREATE SEQUENCE CALBOARDSEQ;

CREATE TABLE CALBOARD(
SEQ NUMBER PRIMARY KEY,
ID VARCHAR2(1000) NOT NULL,
TITLE VARCHAR2(2000) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
MDATE VARCHAR2(12) NOT NULL,
REGDATE DATE NOT NULL

);

SELECT * FROM CALBOARD;


INSERT INTO CALBOARD
VALUES(CALBOARDSEQ.NEXTVAL,?,?,?,?,SYSDATE);

--row_number() over(partition by @ order by)
--@로 group by 해서 그룹 별 rownum 사용할 때

SELECT * FROM(

SELECT(ROW_NUMBER() OVER(PARTITION BY SUBSTR(MDATE,1,8) ORDER BY MDATE)) RN,
SEQ,ID,TITLE,CONTENT,MDATE,REGDATE
FROM CALBOARD
WHERE ID = 'KD' AND SUBSTR(MDATE,1,6)='202001'

)

WHERE RN BETWEEN 1 AND 3;