DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;

DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;
--글번호 그룹번호 그룹순서 제목탭 제목 내용 작성자 작성일
CREATE TABLE ANSWERBOARD(

BOARDNO NUMBER PRIMARY KEY,
GROUPNO NUMBER NOT NULL,
GROUPSEQ NUMBER NOT NULL,
TITLETAB NUMBER NOT NULL,
TITLE VARCHAR2(500) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
WRITER VARCHAR2(100) NOT NULL,
REGDATE DATE NOT NULL,
DELETEORNOT VARCHAR2(2) DEFAULT 'N' NOT NULL,
CONSTRAINT ANSWERBOARD_CHK_DELETE CHECK (DELETEORNOT IN ('Y','N'))

);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSEQ;

INSERT INTO ANSWERBOARD 
VALUES(BOARDNOSEQ.NEXTVAL,GROUPNOSEQ.NEXTVAL,1,0,'1번글','1번글 내용','관리자',SYSDATE,DEFAULT);


INSERT INTO ANSWERBOARD 
VALUES(BOARDNOSEQ.NEXTVAL,GROUPNOSEQ.NEXTVAL,1,0,'2번글','2번글 내용','학생1',SYSDATE);

--1번 글에 답변달기
--UPDATE부터 먼저 해야 한다.부모의 글과 같은 그룹번호, 부모의 그룹순서보다 더 큰 그룹순서인 글들을 찾아서(그룹순서를 +1)

UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1)

INSERT INTO ANSWERBOARD 
VALUES(BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+1,
'RE:1번글','1번글에 답변달기','학생2',SYSDATE);


--삭제 쿼리--
UPDATE ANSWERBOARD SET DELETEORNOT ='Y' WHERE BOARDNO=1;
