DROP SEQUENCE MDBOARDSEQ;
DROP TABLE MDBOARD;

CREATE SEQUENCE MDBOARDSEQ;

CREATE TABLE MDBOARD(
SEQ NUMBER PRIMARY KEY NOT NULL,
WRITER VARCHAR2(1000) NOT NULL,
TITLE VARCHAR2(1000) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
REGDATE DATE NOT NULL

)

SELECT *
FROM MDBOARD;

INSERT INTO MDBOARD
VALUES(MDBOARDSEQ.NEXTVAL,'관리자', 'TEST글','TEST 내용', SYSDATE);

INSERT INTO MDBOARD
VALUES(MDBOARDSEQ.NEXTVAL,'pink floyd', 'dark side of the moon','progressive rock', SYSDATE);